### ISSUE TITLE
[FEATURE REQ] support for debrid-link.com provider

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [sureshfizzy/CineSync#1]
Hello I use another provider than real debrid called debrid-link.com and I would LOVE to see it supported. thanks

**Comment by sureshfizzy** [comment]
Are you mounting with zurg ? If so, then this will work.

**Comment by EsmailELBoBDev2** [comment]
sadly zurg do not support debird-link yet so no

**Comment by sureshfizzy** [comment]
Can you mount it locally with rclone ? If that is possible, then you don't need zurg..

**Comment by EsmailELBoBDev2** [comment]
hmm then documentation should mention that because it said I need zurg...

**Comment by sureshfizzy** [comment]
Can you check with local mount and let me know ? I'll update the doc as well

**Comment by EsmailELBoBDev2** [comment]
I already mounted it locally and here is a proof 
![image](https://github.com/sureshfizzy/CineSync/assets/28893833/84921c0f-ba7c-458b-ab40-aef195d77879)

**Comment by sureshfizzy** [comment]
> I already mounted it locally and here is a proof ![image](https://private-user-images.githubusercontent.com/28893833/332949843-84921c0f-ba7c-458b-ab40-aef195d77879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTE0ODMsIm5iZiI6MTcxNjQxMTE4MywicGF0aCI6Ii8yODg5MzgzMy8zMzI5NDk4NDMtODQ5MjFjMGYtYmE3Yy00NThiLWFiNDAtYWVmMTk1ZDc3ODc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDIwNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxODkxNDZhMTQ5ZmNlYjUwOTE3YmQzN2RhMjU1MzVmNTU2NThmNTY0ZjFhOThkNzk5ZDJlYjgxNmNhMjhhM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VHQKrhSsF3tykuwpiyPDzsC93vkLqfnRaF8n7B2HEKk)

Okay, then I guess it will be good. You can run the script it will work now.

**Comment by EsmailELBoBDev2** [comment]
I will test it and give you a heads up

**Comment by sureshfizzy** [comment]
Sounds good

**Comment by sureshfizzy** [comment]
> I will test it and give you a heads up

I tested it locally, and it works with all local files as well. I have modified the README accordingly.

**Comment by EsmailELBoBDev2** [comment]
oh glad to hear, thanks and sorry for late reply i just have finals and did not study :sweat_smile:

**Comment by sureshfizzy** [comment]
Alright, closing this for now.
