### ISSUE TITLE
Source paths in windows

### ISSUE THREAD

**Issue by Bayharbourbutcher1** [sureshfizzy/CineSync#13]
Hi, thanks for this great program. I have an issue on windows 11, how can i make the script scan 2 source folders one for movies and one for shows?

I tried editing the env file and different ways to declare the source but it doesn't seem to scan both folders.

Thanks in advance

**Comment by sureshfizzy** [comment]
You can add multiple folders with , seperated

Eg: "C:\Zurg\Movies,C:\Zurg\Shows"

**Comment by Bayharbourbutcher1** [comment]
> You can add multiple folders with , seperated
> 
> Eg: "C:\Zurg\Movies,C:\Zurg\Shows"

Thank you, all sorted!

**Comment by sureshfizzy** [comment]
Cool !! Closing this issue now..
