### ISSUE TITLE
How do I fix an incorrect match?

### ISSUE THREAD

**Issue by naonak1** [sureshfizzy/CineSync#14]
I have some titles which when symlinks are created the folder is just the year, rather than any title.

Not sure how to manually match it to a TMDB ID?

**Comment by sureshfizzy** [comment]
A number of fixes have been implemented in the new codebase that should resolve the issue you're experiencing. Please pull the symlinks branch and use it. It's not yet ready for public release but it is stable for now.

https://github.com/sureshfizzy/CineSync/tree/symlinks

**Comment by sureshfizzy** [comment]
@naonak1 Go with new changes, it will solve your issue
