### ISSUE TITLE
Movies in Shows, and Shows in Movies

### ISSUE THREAD

**Issue by Ventrex** [sureshfizzy/CineSync#19]
I love CineSync, but I have an issue he places some movies in shows, and some shows in movies.
I am unable to remove them from plex.

only option is to stop cinesync docker, remove the movies by hand and start cinesync again.
It there something i do wrong?

i only have zurg with rclone, nothing more.

**Comment by sureshfizzy** [comment]
If you are using Docker, the issue is related to permissions. Even when the uid and pid are specified, Docker creates files with the root user. I'll drop a fix maybe by tomorrow.

**Comment by sureshfizzy** [comment]
@Ventrex can you be more specific about Movies in Shows ?

**Comment by Ventrex** [comment]
I reinstalled everything so sadly no examples atm.

But as example there where 900 episodes of a show named 2 broke girls. But most episodes where from adventure time. 
Found out that they where specials like S01E00 or S00E01. But placed in the wrong folder.

Also a folder called 1990 and 1995 which contained a movie from 1990 and 1995.

The movies folder contained multiple series. All in a folder. With strange names.

After exclude the shows and movies folder it looks beter. (So /mnt/CineSync/Shows/Shows and /mnt/CineSync/Movies/Movies)

looks like when he doesn’t know the show or movie name he place it there.

**Comment by sureshfizzy** [comment]
Looks like I need to cleanup the structure a bit,  if the file doesn't have any resolution it ends up being placed inside mnt/CineSync/Movies/Movies or shows.

**Comment by sureshfizzy** [comment]
Added new structure options on symlinks branch codebase, try overriding the source structure with the available options on the env file (don't use docker build it hasn't been updated with it yet)

**Comment by Ventrex** [comment]
Sorry! I did this and it looks good now!
Found another thing, but will make a new issue (or more a request)

**Comment by Ventrex** [comment]
Looks like they are now working better
