### ISSUE TITLE
Request: Option to disable Features and Bonus in .env

### ISSUE THREAD

**Issue by Ventrex** [sureshfizzy/CineSync#23]
Is it possible to disable importing featurettes and bonus items located in the movie/show folder?

For example I had The Rock (1996) which contained multiple Featurettes and Bonus items.
Plex tried to import them as a movie/show and links another movie/show to it.

If it is possible maybe add an option in .env to enable/disable featurettes and bonus items?

Most of the time the files are in the same folder with the movie or in a subfolder, maybe add a check which file is the biggest or duration is the longest as the main video.
And for shows they are mostly called S01E00 or in a special folder.

**Comment by sureshfizzy** [comment]
I can add those along the SKIP_EXTRAS variable. featurettes, bonus anything else apart from this ?

**Comment by sureshfizzy** [comment]
@Ventrex it will work as per your needs, images has been updated

**Comment by Ventrex** [comment]
Already? Wow you are fast!

**Comment by sureshfizzy** [comment]
> Already? Wow you are fast!

Default is set to 100mb you can reduce or increase it in env file
