### ISSUE TITLE
Symlinks structure

### ISSUE THREAD

**Issue by Bayharbourbutcher1** [sureshfizzy/CineSync#24]
Thanks for this great tool first of all! Is it possible to customise the output directory structure? I'd like to use your tool to compliment my Riven stack. I want to only create symlinks in the destination Riven directory e.g. premade Movies and Shows folder without 4k etc.

I am on linux.

**Comment by sureshfizzy** [comment]
Hello, right now it creates a new folder names Cinesync under destination directory and further folders. Are you saying you want to override that particular structure starting from Cinesync folder ?

**Comment by Bayharbourbutcher1** [comment]
> Hello, right now it creates a new folder named Cinesync under destination directory and further folders. Are you saying you want to override that particular structure starting from Cinesync folder ? 

Yes thats correct. In my destination directory I already have the movies and shows folder. Id like cinesync to output to those two Riven folders instead of creating separate folders.

**Comment by sureshfizzy** [comment]
Are those files based on symlinks ? Can you send me a sample folder structure to see how it looks. Never used Riven before.

**Comment by Bayharbourbutcher1** [comment]
> Are those files based on symlinks ? Can you send me a sample folder structure to see how it looks. Never used Riven before.

Yes those folders contain symlinks to my real debrid mount. Riven puts them there after processing the requests. There are 4 folders in dir anime_movies, anime_shows, movies and shows.

**Comment by sureshfizzy** [comment]
> > Are those files based on symlinks ? Can you send me a sample folder structure to see how it looks. Never used Riven before.
> 
> Yes those folders contain symlinks to my real debrid mount. Riven puts them there after processing the requests. There are 4 folders in dir anime_movies, anime_shows, movies and shows.

If those 4 folders are fixed then ig it's possible to bring it up. But I also need to make sure that db is not crashing at that point. I'll make Changes and test it out. Between, Riven only uses imdb folder I'd right ?

**Comment by Bayharbourbutcher1** [comment]
> > > Are those files based on symlinks ? Can you send me a sample folder structure to see how it looks. Never used Riven before.
> > 
> > Yes those folders contain symlinks to my real debrid mount. Riven puts them there after processing the requests. There are 4 folders in dir anime_movies, anime_shows, movies and shows.
> 
> If those 4 folders are fixed then ig it's possible to bring it up. But I also need to make sure that db is not crashing at that point. I'll make Changes and test it out. Between, Riven only uses imdb folder I'd right ?

Yes, Riven uses imdb folder IDs. Let me know if you want me to test anything. Thanks 😊

**Comment by sureshfizzy** [comment]
Then I need to check on IMDb support first. Cinesync only supports tmdb at the moment. It will mess up with your Riven destination structure with tmdb and IMDb ID's (mixed). I'll check on bringing up IMDb api calls and update the script further. Sounds good ?

**Comment by Bayharbourbutcher1** [comment]
> Then I need to check on IMDb support first. Cinesync only supports tmdb at the moment. It will mess up with your Riven destination structure with tmdb and IMDb ID's (mixed). I'll check on bringing up IMDb api calls and update the script further. Sounds good ?

That's great thanks
