### ISSUE TITLE
Q: How to run full library autoscan once?

### ISSUE THREAD

**Issue by ppogorze** [sureshfizzy/CineSync#26]
Hello.
I want to create script hook for zurg, that will fire full library autoscan once.
No need to enable realtime monitor, which on my arch system+fish+conda doesn't work.
Any tips how to write shell script or which python file can i run with parameters to achieve that?

Any help appreciated.
Thank you.

**Comment by ppogorze** [comment]
NVM, using Docker image without issues.

**Comment by sureshfizzy** [comment]
Once the full scan is done, auto scan monitor mode will be triggered so you don't need to worry about it :)
