### ISSUE TITLE
Running as root

### ISSUE THREAD

**Issue by Bayharbourbutcher1** [sureshfizzy/CineSync#27]
I just tried to turn on real time monitoring on my Linux machine and script needs to run as root. Is this by design? Couldn't see it anywhere in the read.me.

**Comment by sureshfizzy** [comment]
You can avoid realtime monitoring script, Just run a full scan with the main file or use the docker image, it has a inbuilt monitoring tool which doesn't need root.

**Comment by Bayharbourbutcher1** [comment]
> You can avoid realtime monitoring script, Just run a full scan with the main file or use the docker image, it has a inbuilt monitoring tool which doesn't need root.

Ah cool, ill give docker a go then. Thanks

**Comment by sureshfizzy** [comment]
let me know if it goes good

**Comment by Bayharbourbutcher1** [comment]
Yes, working very well in docker thanks Suresh
