### ISSUE TITLE
Anime show patterns are counted as Movies

### ISSUE THREAD

**Issue by vpierre1776** [sureshfizzy/CineSync#29]
Hi. I'm having an issue where shows, in this case Anime  shows are being sorted / placed in the movie directories. Is there any thing I can do on my end to fix this? I have added a vid of the issue. Logs same fine, no errors. 

https://streamable.com/sbeef2

**Comment by sureshfizzy** [comment]
is it happening only for anime's ? if yes then it makes sense because the script it struggling to handle anime files due to many improper names in between. but we can see why it is detecting as shows instead of movies. can you provide the logs as below ?

Steps:

1) Pick any anime show from source file and get inside the project directory.
2) Run the script in this way

python3 MediaHub/main.py "full/path/to/anime/show" --auto-select

3) Share the output here, Also before executing the file make sure you delete them from destination if it is already present.

**Comment by vpierre1776** [comment]
Here is what got back. [https://pastebin.com/4mXN4U7C](url)

**Comment by sureshfizzy** [comment]
You need to pass the zurg source file there and not the cinesync folder.

Also if possible can you share the og name of the series and following episode names (just 1-2 names is fine)

**Comment by vpierre1776** [comment]
> You need to pass the zurg source file there and not the cinesync folder.
> 
> Also if possible can you share the og name of the series and following episode names (just 1-2 names is fine)

I ran the above command on the   zurg __all__ folder nount,  here is the output.... 
https://pastebin.com/Mhzn8Sxs 

The OG name of the series is "Fullmetal Alchemist: Brotherhood"  
here is the link on TMDB "https://www.themoviedb.org/tv/31911-fullmetal-alchemist-brotherhood?language=en-US"

Episode names of files in mount:   
"[Ryuuga] - Fullmetal Alchemist_ Brotherhood  - 01 - Fullmetal Alchemist [1080p].mkv"
"[Ryuuga] - Fullmetal Alchemist_ Brotherhood  - 02 - The First Day [1080p].mkv"

**Comment by sureshfizzy** [comment]
Thanks, I'll check on this and let you know soon.

**Comment by sureshfizzy** [comment]
The current implementation of the code is designed to identify and categorize episode names based on specific patterns. For example, the following filenames:

"[Ryuuga] - Fullmetal Alchemist_ Brotherhood - 01 - Fullmetal Alchemist [1080p].mkv"
"[Ryuuga] - Fullmetal Alchemist_ Brotherhood - 02 - The First Day [1080p].mkv"

Currently, the function at this link (https://github.com/sureshfizzy/CineSync/blob/main/MediaHub/processors/symlink_creator.py#L67) checks for specific patterns to determine whether the file should be classified as a movie or a show. However, in the case of the filenames provided, the function fails to recognize any distinguishing patterns that would categorize them as a series. As a result, these episode files are incorrectly classified as movies.

It’s crucial to tweak the pattern recognition logic to correctly identify series episodes, but we must proceed with caution. Adjustments might unintentionally affect the classification of movie files. For instance, consider these movie filenames:

"01. The Expendables [2010] [Extended Director's Cut] 1080p BDRip x265 DTS-HD MA 7.1 Kira [SEV].mkv"
"01. V.H.S. [2012] 1080p BDRip x265 DTS-HD MA 5.1 Kira [SEV].mkv"

Given the potential for misclassification, it would be better to select a different file that clearly distinguishes between series and movies. This way, we can refine the logic without risking the integrity of movie classifications.

**Comment by sureshfizzy** [comment]
> Got you. Out of curiosity, would it be possible to match a file name to the ones on Debrid Media Manager, if ran locally, to resolve what the actual movie / series it is?

But the actual question is, how does the file know if it was taken from dmm or another source? There will be no connectivity to dmm once it comes out of the box.

**Comment by vpierre1776** [comment]
> > Got you. Out of curiosity, would it be possible to match a file name to the ones on Debrid Media Manager, if ran locally, to resolve what the actual movie / series it is?
> 
> But the actual question is, how does the file know if it was taken from dmm or another source? There will be no connectivity to dmm once it comes out of the box.

True.

**Comment by vpierre1776** [comment]
sure thing I'll put some together 

> @vpierre1776 I've started working on this, it would be good if you drop few more patterns.
> 
> Foldername & filename

sure thing I'll put some together

**Comment by vpierre1776** [comment]
> sure thing I'll put some together
> 
> > @vpierre1776 I've started working on this, it would be good if you drop few more patterns.
> > Foldername & filename
> 
> sure thing I'll put some together


Anime Shows 

1. "/mnt/cinesync_media/CineSync/Movies/FullHD/HorribleSubs Assassination Classroom (1080)/" 
[HorribleSubs] Assassination Classroom S2 - 01 [1080p].mkv

2./mnt/cinesync_media/CineSync/Movies/FullHD/Erai raws Beastars 2nd (1080)/
[Erai-raws] Beastars 2nd Season - 05 [1080p][Multiple Subtitle][9EE7A542].mkv

3./mnt/cinesync_media/CineSync/Movies/FullHD/Salieri Blue Lock (1080)/
[Salieri] Blue Lock S1 - 16 (1080p) (HDR) [Dual Audio].mkv

4./mnt/cinesync_media/CineSync/Movies/FullHD/Erai raws Boku no Hero Academia 7th (1080)/
[Erai-raws] Boku no Hero Academia 7th Season - 10 [1080p][HEVC][Multiple Subtitle][7D01DBF7].mkv

5./mnt/cinesync_media/CineSync/Movies/FullHD/sam Chainsaw Man BD (1080)/
[sam] Chainsaw Man - 07 [BD 1080p FLAC] [46DF814D].mkv

6./mnt/cinesync_media/CineSync/Movies/FullHD/sam One Punch Man (1080)/
[sam] One Punch Man S2 - 11 [BD 1080p FLAC] [38B07BC9].mkv

7./mnt/cinesync_media/CineSync/Movies/FullHD/HorribleRips Overlord (1080)/
[HorribleRips] Overlord S1 - 10 [1080p].mkv

8./mnt/cinesync_media/CineSync/Movies/FullHD/Erai raws ReLIFE 01 ~ 13 (1080)/
[Erai-raws] ReLIFE - 04 [1080p][Multiple Subtitle].mkv

9./mnt/cinesync_media/CineSync/Movies/FullHD/HorribleSubs Shokugeki no Soma (1080)/
[HorribleSubs] Shokugeki no Soma S3 - 20 [1080p].mkv

10./mnt/cinesync_media/CineSync/Movies/FullHD/Anime Time Tate no Yuusha no Nariagari (1080)/
[Anime Time] Tate no Yuusha no Nariagari Season 2 - 09 [1080p][HEVC 10bit x265][AAC][Multi Sub].mkv

**Comment by sureshfizzy** [comment]
> > sure thing I'll put some together
> > > @vpierre1776 I've started working on this, it would be good if you drop few more patterns.
> > > Foldername & filename
> > 
> > 
> > sure thing I'll put some together
> 
> Anime Shows
> 
> Zurg / RD Mount folder name filename
> 
> 1. [Salieri] Blue Lock S1 - BD (1080p) (HDR) [Dual Audio]
>    [Salieri] Blue Lock S1 - 16 (1080p) (HDR) [Dual Audio].mkv
> 2. [Erai-raws] ReLIFE - 01 ~ 13 [1080p][Multiple Subtitle]
>    [Erai-raws] ReLIFE - 04 [1080p][Multiple Subtitle].mkv
> 3. [Anime Time] Tate no Yuusha no Nariagari Season 2  [1080p][HEVC 10bit x265][AAC][Multi Sub] [Weekly] The Rising Of The Shield Hero Season 2
>    [Anime Time] Tate no Yuusha no Nariagari Season 2 - 09 [1080p][HEVC 10bit x265][AAC][Multi Sub].mkv
> 4. [Salieri] Blue Lock S1 - BD (1080p) (HDR) [Dual Audio]
>    [Salieri] Blue Lock S1 - 13 (1080p) (HDR) [Dual Audio].mkv
> 5. Death Note (Complete Series) [1080p] (Dual Audio)
>    Behind the Scenes - Near and Matsuda (English Dialogue).mkv
> 
> _(folder is named like a file, has an . extensions in RD zurg mount, not the only one like this)_ 6. [Erai-raws] Boku no Hero Academia 7th Season - 10 [720p][Multiple Subtitle][E638745D].mkv [Erai-raws] Boku no Hero Academia 7th Season - 10 [720p][Multiple Subtitle][E638745D].mkv
> 
> 7. [HorribleRips] Overlord S1 [1080p]
>    [HorribleRips] Overlord S1 - 10[1080p].mkv
> 8. [HorribleSubs] Assassination Classroom S2 - 01 [1080p].mkv
>    [HorribleSubs] Assassination Classroom S2 - 01 [1080p].mkv
> 9. [sam] Chainsaw Man [BD 1080p FLAC]
>    [sam] Chainsaw Man - 07 [BD 1080p FLAC] [46DF814D].mkv
> 10. [sam] One Punch Man S2 [BD 1080p FLAC]
>     [sam] One Punch Man S2 - 11 [BD 1080p FLAC] [38B07BC9].mkv

Thank you, at this point 5th one seems pure evil, it might be super hard to identify. I can try for rest of the things.

**Comment by vpierre1776** [comment]
> > > sure thing I'll put some together
> > > > @vpierre1776 I've started working on this, it would be good if you drop few more patterns.
> > > > Foldername & filename
> > > 
> > > 
> > > sure thing I'll put some together
> > 
> > 
> > Anime Shows
> > Zurg / RD Mount folder name filename
> > 
> > 1. [Salieri] Blue Lock S1 - BD (1080p) (HDR) [Dual Audio]
> >    [Salieri] Blue Lock S1 - 16 (1080p) (HDR) [Dual Audio].mkv
> > 2. [Erai-raws] ReLIFE - 01 ~ 13 [1080p][Multiple Subtitle]
> >    [Erai-raws] ReLIFE - 04 [1080p][Multiple Subtitle].mkv
> > 3. [Anime Time] Tate no Yuusha no Nariagari Season 2  [1080p][HEVC 10bit x265][AAC][Multi Sub] [Weekly] The Rising Of The Shield Hero Season 2
> >    [Anime Time] Tate no Yuusha no Nariagari Season 2 - 09 [1080p][HEVC 10bit x265][AAC][Multi Sub].mkv
> > 4. [Salieri] Blue Lock S1 - BD (1080p) (HDR) [Dual Audio]
> >    [Salieri] Blue Lock S1 - 13 (1080p) (HDR) [Dual Audio].mkv
> > 5. Death Note (Complete Series) [1080p] (Dual Audio)
> >    Behind the Scenes - Near and Matsuda (English Dialogue).mkv
> > 
> > _(folder is named like a file, has an . extensions in RD zurg mount, not the only one like this)_ 6. [Erai-raws] Boku no Hero Academia 7th Season - 10 [720p][Multiple Subtitle][E638745D].mkv [Erai-raws] Boku no Hero Academia 7th Season - 10 [720p][Multiple Subtitle][E638745D].mkv
> > 
> > 7. [HorribleRips] Overlord S1 [1080p]
> >    [HorribleRips] Overlord S1 - 10[1080p].mkv
> > 8. [HorribleSubs] Assassination Classroom S2 - 01 [1080p].mkv
> >    [HorribleSubs] Assassination Classroom S2 - 01 [1080p].mkv
> > 9. [sam] Chainsaw Man [BD 1080p FLAC]
> >    [sam] Chainsaw Man - 07 [BD 1080p FLAC] [46DF814D].mkv
> > 10. [sam] One Punch Man S2 [BD 1080p FLAC]
> >     [sam] One Punch Man S2 - 11 [BD 1080p FLAC] [38B07BC9].mkv
> 
> Thank you, at this point 5th one seems pure evil, it might be super hard to identify. I can try for rest of the things.

Appreciated. I can post more if it helps.

**Comment by sureshfizzy** [comment]
I've solved it, The anime accuracy is almost perfect and can now handle even the most unusual names. You can try using the anime-fix branch and enable ANIME_SCAN=true in the environment settings. If you prefer using a Docker image, you can use this one:

sureshfizzy/cinesync:anime

There are still a few minor issues, but I’ll update them tomorrow.

**Comment by vpierre1776** [comment]
> I've solved it, The anime accuracy is almost perfect and can now handle even the most unusual names. You can try using the anime-fix branch and enable ANIME_SCAN=true in the environment settings. If you prefer using a Docker image, you can use this one:
> 
> sureshfizzy/cinesync:anime
> 
> There are still a few minor issues, but I’ll update them tomorrow.

Cool!. I have spun up a new VM and scanning everything in again using docker. I'll let you know how it goes.

**Comment by sureshfizzy** [comment]
> > I've solved it, The anime accuracy is almost perfect and can now handle even the most unusual names. You can try using the anime-fix branch and enable ANIME_SCAN=true in the environment settings. If you prefer using a Docker image, you can use this one:
> > sureshfizzy/cinesync:anime
> > There are still a few minor issues, but I’ll update them tomorrow.
> 
> Cool!. I have spun up a new VM and scanning everything in again using docker. I'll let you know how it goes.

Perfect, let me know if you encounter any more new patterns. I'm currently working on rename tags (exact way which arr gives you ) and others stuffs over that branch. Once it is stable I'll merge them to main branch.

**Comment by vpierre1776** [comment]
> > > I've solved it, The anime accuracy is almost perfect and can now handle even the most unusual names. You can try using the anime-fix branch and enable ANIME_SCAN=true in the environment settings. If you prefer using a Docker image, you can use this one:
> > > sureshfizzy/cinesync:anime
> > > There are still a few minor issues, but I’ll update them tomorrow.
> > 
> > 
> > Cool!. I have spun up a new VM and scanning everything in again using docker. I'll let you know how it goes.
> 
> Perfect, let me know if you encounter any more new patterns. I'm currently working on rename tags (exact way which arr gives you ) and others stuffs over that branch. Once it is stable I'll merge them to main branch.

What ever you tweaked really did the job. I could only find 4 Anime shows out of over 1k it's scanned in the movie section, before it was dozens upon dozens. Here are some patterns found.

1 . Kuroko no Basket 3rd Season [1080]
     [Cleo]Kuroko_no_Basket_3rd_Season_-_07_(10bit_BD1080p_x265).mkv


  2.  Ansatsu Kyoushitsu 2nd Season       [Cleo]Ansatsu_Kyoushitsu_2nd_Season_-_17_(Dual Audio_10bit_BD720p).mkv

3. That Time I Got Reincarnated as a Slime Season3 - E1 Demon and Scheme 1080p B-Global WEB-DL x264 [Japanese] (AAC 2.0) MSubs_ToonsHub_
       That Time I Got Reincarnated as a Slime Season3 - E1 Demon and Scheme 1080p B-Global WEB-DL x264 [Japanese] (AAC 2.0) MSubs_ToonsHub_.mkv

**Comment by sureshfizzy** [comment]
> > > > I've solved it, The anime accuracy is almost perfect and can now handle even the most unusual names. You can try using the anime-fix branch and enable ANIME_SCAN=true in the environment settings. If you prefer using a Docker image, you can use this one:
> > > > sureshfizzy/cinesync:anime
> > > > There are still a few minor issues, but I’ll update them tomorrow.
> > > 
> > > 
> > > Cool!. I have spun up a new VM and scanning everything in again using docker. I'll let you know how it goes.
> > 
> > 
> > Perfect, let me know if you encounter any more new patterns. I'm currently working on rename tags (exact way which arr gives you ) and others stuffs over that branch. Once it is stable I'll merge them to main branch.
> 
> Awsome, whatever you tweaked really did the job. I could only find 4 Anime shows out of over 1k movie scanned in the movie section, before it was dozens upon dozens. Here are some patterns found.
> 
> 1 . Kuroko no Basket 3rd Season [1080] [Cleo]Kuroko_no_Basket_3rd_Season_-_07_(10bit_BD1080p_x265).mkv
> 
> 2. Ansatsu Kyoushitsu 2nd Season    
>    [Cleo]Ansatsu_Kyoushitsu_2nd_Season_-_17_(Dual Audio_10bit_BD720p).mkv
> 3. That Time I Got Reincarnated as a Slime Season3 - E1 Demon and Scheme 1080p B-Global WEB-DL x264 [Japanese] (AAC 2.0) MSubs_ToonsHub_
>    That Time I Got Reincarnated as a Slime Season3 - E1 Demon and Scheme 1080p B-Global WEB-DL x264 [Japanese] (AAC 2.0) MSubs_ToonsHub_.mkv

Thank you for the updates! I appreciate it. These patterns have now been addressed and you can pull the image again and give a try

**Comment by sureshfizzy** [comment]
@vpierre1776, The new release is stable and resolves most pattern issues. I'll be closing this issue for now. If you encounter any further problems, please join our Discord for troubleshooting: [https://discord.gg/BtZYTCQtAR](https://discord.gg/BtZYTCQtAR).
