### ISSUE TITLE
On windows it gives me an error

### ISSUE THREAD

**Issue by coccobellof5** [sureshfizzy/CineSync#30]
`Version 2.0 - Last updated on 2024-09-08

Full Library Scan Options:
1) Auto Scan
2) Manual Scan (Use only when TMDB ID is enabled)
3) Back to Main Menu
Select an option: 1
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\CineSync\CineSync.py", line 346, in <module>
    main()
    ~~~~^^
  File "C:\Users\Administrator\Documents\CineSync\CineSync.py", line 335, in main
    execute_full_library_scan()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\Documents\CineSync\CineSync.py", line 198, in execute_full_library_scan
    subprocess.run(['python3', LIBRARY_SCRIPT, '--auto-select'], check=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1548, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

Hi, I'm having this problem.
I think I configured everything correctly, but it doesn't work...


```
# Source directory for input files
SOURCE_DIR="C:\zurg\"

# Destination directory for output files
DESTINATION_DIR="C:\test\filmlink\"
```

**Comment by sureshfizzy** [comment]
Hi, from which this build was taken ? did you pick from releases or made a fresh clone ?

**Comment by coccobellof5** [comment]
> Hi, from which this build was taken ? did you pick from releases or made a fresh clone ?

I performed the commands as per the readme guide.
I don't know if there are other unwritten operations...

**Comment by sureshfizzy** [comment]
Logs will be generated in the same folder, if found, please share them as they will be useful for debugging.

**Comment by coccobellof5** [comment]
> Logs will be generated in the same folder, if found, please share them as they will be useful for debugging.

I just tried pasting your entire python script to chatgpt, it fixed a little bit and now the script is working.

But Plex doesn't even detect any content...

**Comment by coccobellof5** [comment]
> Logs will be generated in the same folder, if found, please share them as they will be useful for debugging.

I found the problem... too bad it's not mentioned in the readme. The path of the directories must be with /, \ is not good.

However, even though I scanned all my realdebrid, it doesn't load the contents on Plex.
I selected the folder with the symlinks but it doesn't work...
Are there solutions?

**Comment by sureshfizzy** [comment]
> > Logs will be generated in the same folder, if found, please share them as they will be useful for debugging.
> 
> I found the problem... too bad it's not mentioned in the readme. The path of the directories must be with /, \ is not good.
> 
> However, even though I scanned all my realdebrid, it doesn't load the contents on Plex. I selected the folder with the symlinks but it doesn't work... Are there solutions?

Sorry for the slashes I'll update the Readme soon, and if we are talking about symlinks, Plex doesn't support symlinks on windows which is a known issue and there is no official support for it right now. You can either use jellyfin or some other apps if you want.

Second solution would be running Plex through docker on windows.

**Comment by sureshfizzy** [comment]
The latest code should run smoothly on Windows. Regarding symlinks in Plex, it's a known limitation on the Windows platform, and they don't work as expected. Closing this issue for now.
