### ISSUE TITLE
Custom folder structure 

### ISSUE THREAD

**Issue by Bayharbourbutcher1** [sureshfizzy/CineSync#34]
I would love to be able to customise the destination folder structure e.g. have just 2 folders Movies and Shows with everything symlink just going into them. Currently I am using Torbox which has no folder structure at source and with cinesync I have multiple folders on destination.  I'd love to be able to simplify it.

**Comment by sureshfizzy** [comment]
That makes sense for torbox, so only Movies and shows folder on destination is enough right ?

**Comment by Bayharbourbutcher1** [comment]
Yes, that would be amazing, thanks

**Comment by sureshfizzy** [comment]
Hi @Bayharbourbutcher1,

I’ve added a few new features to the anime-fix branch, including ANIME_SCAN and CINESYNC_LAYOUT. When you set CINESYNC_LAYOUT to true, it will function as you expected.

For local testing, clone the anime-fix branch, and if you need a Docker image, you can use:

docker pull sureshfizzy/cinesync:anime

I’ll merge this into the main branch after testing a few more things. Let me know if you have any questions or run into issues!

**Comment by Bayharbourbutcher1** [comment]
Thanks Suresh, ill do a docker pull and test it out. So setting that variable to true will let me create movies and shows folders?

**Comment by Bayharbourbutcher1** [comment]
Just did a new pull, getting errors:

[![Screenshot_20241207_204327_Firefox.jpg](https://github.com/user-attachments/assets/c63f70d8-04bc-432a-902a-1ef7864d1f10)

**Comment by sureshfizzy** [comment]
My bad, can you repull it again, it will work

**Comment by Bayharbourbutcher1** [comment]
Pulled it again, worked beautifully 😍
Thank you so much for implementing it so quickly.

**Comment by sureshfizzy** [comment]
> Pulled it again, worked beautifully 😍 Thank you so much for implementing it so quickly.

The new implementation has the highest accuracy for animes which can filter very odd patterns, let me know if you face any issues. Once it is stable I'll merge it to main branch.

**Comment by Bayharbourbutcher1** [comment]
Alright,  ill keep an eye out for any issues. One more thing, I  was thinking of (happy to open another issue) if it was possible for cinesync to detect a broken symlink and remove it?

**Comment by sureshfizzy** [comment]
> Alright, ill keep an eye out for any issues. One more thing, I was thinking of (happy to open another issue) if it was possible for cinesync to detect a broken symlink and remove it?

That is already implemented, when CineSync is running, if the original file is removed, it will automatically delete any broken symlinks and empty directories.

**Comment by Bayharbourbutcher1** [comment]
Ah okay, i think the issue is torbox rclone mount doesn't reflect that the file is removed or broken hence CS assumes its still present and I get errors when i try to play items from plex/jellfyin

**Comment by sureshfizzy** [comment]
> Ah okay, i think the issue is torbox rclone mount doesn't reflect that the file is removed or broken hence CS assumes its still present and I get errors when i try to play items from plex/jellfyin

That makes sense, only if the mount is refreshed and the original folder is deleted, Cinesync will  be able to detect the change. At this point, the Torbox mount may be experiencing delays in reflecting the actual file status.

**Comment by Bayharbourbutcher1** [comment]
Yes, they do have a fair share of issues at the moment. I am happy with my current workflow and CS is a very good tool. Thanks again.

**Comment by sureshfizzy** [comment]
> Yes, they do have a fair share of issues at the moment. I am happy with my current workflow and CS is a very good tool. Thanks again.

I have similar issues with my usenet and i did a temporary workaround for it.

```#!/bin/bash

# Function to display a countdown
countdown() {
    local seconds=$1
    while [ $seconds -gt 0 ]; do
        echo -ne "Next refresh in $seconds seconds...\r"
        sleep 1
        ((seconds--))
    done
    echo -ne "\n"  # Move to a new line after the countdown
}

# Infinite loop to run the command every 30 minutes
while true; do
    # Display the current time and status message
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting rclone refresh..."
    
    # Run the rclone command and capture the output
    if rclone rc vfs/refresh recursive=true --rc-addr=localhost:5572 -vv; then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] rclone refresh completed successfully."
    else
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] rclone refresh failed."
    fi
    
    # Countdown for the next refresh (30 minutes = 1800 seconds)
    countdown 1800
done```

Update the --rc-addr=localhost:5572 to match your configuration, mine is set to 5572. Ensure this address is also added to the rclone.conf file on Torbox. Additionally, increase the timeout as needed. Save the script in a .sh file and run it in the background. This will refresh the folders at the interval you specify (every X minutes)

**Comment by Bayharbourbutcher1** [comment]
Ah cool, ill check this out. Thanks

**Comment by JourneyOver** [comment]
@sureshfizzy Would it be possible to add an option for users to define their own path layouts, rather than being only the CineSync layout or the source directory? My directory structure uses `TV Shows` for all my local stuff instead of `Shows`, and using the tool as it stands would require me to completely reorganize my existing layout—a change I’d prefer to avoid having to do.

The only alternative would be to make a personal fork, which I’d rather not do tbh. Having this flexibility built into the tool would make it far more usable and adaptable for people with different directory structures. I hope this can be considered as an improvement!

**Comment by sureshfizzy** [comment]
> @sureshfizzy Would it be possible to add an option for users to define their own path layouts, rather than being only the CineSync layout or the source directory? My directory structure uses `TV Shows` for all my local stuff instead of `Shows`, and using the tool as it stands would require me to completely reorganize my existing layout—a change I’d prefer to avoid having to do.
> 
> The only alternative would be to make a personal fork, which I’d rather not do tbh. Having this flexibility built into the tool would make it far more usable and adaptable for people with different directory structures. I hope this can be considered as an improvement!

Intresting, so at this point it shouldn't use the folder CineSync too right ?

For eg: /home/ubuntu/TV Shows 

As per your expectations, When defined in custom folder path,  the symlink must be at this location. Correct me if I'm wrong.

**Comment by JourneyOver** [comment]
@sureshfizzy Hmm I believe so yes, it could be like that for only the `custom_folders` option unless the user specifically sets the custom_folder to something like `CineSync/TV Shows` or a similar structure. I'm mainly using shows as an example but this could be expanded ofc to movies and anime as well.

so it's mainly come out like `dest_dir, custom_folder, show_folder`.

For example if my `dest_dir` was `/mnt/Abyss/Media` and the `custom_folder` was `TV Shows` then the `base_dest_path` would end up be something like `/mnt/Abyss/Media/TV Shows/{Name of show}` in the end for the symlink.

**Comment by sureshfizzy** [comment]
> @sureshfizzy Hmm I believe so yes, it could be like that for only the `custom_folders` option unless the user specifically sets the custom_folder to something like `CineSync/TV Shows` or a similar structure but I feel like they could just instead have the `CineSync` part be apart of the `source_dir` instead if the user decides to use the `custom_folders` option. I'm mainly using shows as an example but this could be expanded ofc to movies and anime as well (though we would need to create options specifically for them as well (eg: `custom_shows_folder`, `custom_movies_folder`, `custom_anime_folder`).
> 
> so it's mainly comes out like `dest_dir, custom_folder, show_folder`.
> 
> For example if my `dest_dir` was `/mnt/Abyss/Media` and the `custom_folder` was `TV Shows` then the `base_dest_path` would end up be something like `/mnt/Abyss/Media/TV Shows/{Name of show}` in the end for the symlink.

I'll look forward to it, thanks

**Comment by sureshfizzy** [comment]
@JourneyOver, After updating the environment and pulling the new code, everything will function as you had hoped. The ani folders is now somewhat complicated because the backbone depends on tmdb, but I will investigate that in the upcoming versions. You also need to adjust your custom paths and enable CINESYNC_LAYOUT for the structure to work.

for eg:

CUSTOM_SHOW_FOLDER="TV Shows"         -> /destination/TV Shows/{show_name}
CUSTOM_MOVIE_FOLDER="Movies/HD"       -> /destination/Movies/HD/{movie_name}

leaving blank will use default paths (CineSync/Shows and CineSync/Movies)

**Comment by JourneyOver** [comment]
@sureshfizzy Great, I'll set up a container and test things out when I can get some free time, should be able to do so either later today or tomorrow.

**Comment by JourneyOver** [comment]
Also random question @sureshfizzy before I set this up later to test things and all that: Regarding the [Volumes section](https://github.com/sureshfizzy/CineSync/wiki/Volumes) in a Docker container, I haven't really worked with symlinks (either absolute or relative) in docker containers yet. On my host system, both my local media (and also where I'd like symlinks to be stored) and the Zurg directory are located in `/mnt/`. For example:
- Symlinks would go under `/mnt/Abyss/Media/{TV Shows, Movies}/{Show, Movie Name}`
- Zurg is located at `/mnt/Zurg`

However, I have other data in the `/mnt` directory that I don’t want to mount in any Docker containers. Therefore, I'd prefer not to mount the entire `/mnt` directory, as described in the same link mentioned above under [solution for mounting full directories](https://github.com/sureshfizzy/CineSync/wiki/Volumes#solution-mount-full-directories).

What should the volume mappings look like in this case? Also, should I probably use relative symlinks instead of absolute ones due to this?

**Comment by sureshfizzy** [comment]
> Also random question @sureshfizzy before I set this up later to test things and all that: Regarding the [Volumes section](https://github.com/sureshfizzy/CineSync/wiki/Volumes) in a Docker container, I haven't really worked with symlinks (either absolute or relative) in docker containers yet. On my host system, both my local media (and also where I'd like symlinks to be stored) and the Zurg directory are located in `/mnt/`. For example:
> 
> * Symlinks would go under `/mnt/Abyss/Media/{TV Shows, Movies}/{Show, Movie Name}`
> * Zurg is located at `/mnt/Zurg`
> 
> However, I have other data in the `/mnt` directory that I don’t want to mount in any Docker containers. Therefore, I'd prefer not to mount the entire `/mnt` directory, as described in the same link mentioned above under [solution for mounting full directories](https://github.com/sureshfizzy/CineSync/wiki/Volumes#solution-mount-full-directories).
> 
> What should the volume mappings look like in this case? Also, should I probably use relative symlinks instead of absolute ones due to this?

This will break the structure on Plex, although cinesync will create the links, for Plex/jellyfin you need to mount the entire directory for that symlink to work since it is the nature of symlinks. Avoiding that will make media unavailable.

Another solution would be create a new folder something like /zurg and attach your mount at this point and use absolute symlinks.

**Comment by sureshfizzy** [comment]
> @sureshfizzy so if I was to do your `solution` would it end up looking something along the lines of:
> 
> ```
>     volumes:
>       - /mnt/Abyss/Media:/media
>       - /Zurg:/zurg
> ```
> 
> then for both the Plex and CineSync containers? or would I need to do something like:
> 
> ```
>     volumes:
>       - /mnt/Abyss/Media:/mnt/Abyss/Media
>       - /Zurg:/Zurg
> ```

Yea this will work

**Comment by JourneyOver** [comment]
Going to assume you mean the first method when you say `Yea this will work`? hopefully xD If so then great, I'll let you know how everything goes later/tomorrow when I get around to setting things up!

**Comment by sureshfizzy** [comment]
> Going to assume you mean the first setup when you say `Yea this will work`? hopefully xD If so then great, I'll let you know how everything goes later/tomorrow when I get around to setting things up!

Let me know about it, also you could join the discord for futher troubleshooting if needed.

**Comment by JourneyOver** [comment]
So got everything up and running and so far it's working great! So thanks for the help in learning more about symlink stuff when it comes to docker as I never had previously messed with symlink stuff other than outside of docker :P

**Comment by sureshfizzy** [comment]
> So got everything up and running and so far it's working great! So thanks for the help in learning more about symlink stuff when it comes to docker as I never had previously messed with symlink stuff other than outside of docker :P

Good to hear :)
