### ISSUE TITLE
BUG: Null resolution throws error stack in logs.

### ISSUE THREAD

**Issue by arao** [sureshfizzy/CineSync#37]
stack trace

```
Final cleaned query: 'American Dad! - 7x01 - 100 A D (1)'
2024-12-14 10:12:54 [ERROR] Task failed with exception: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/<>/CineSync/MediaHub/processors/symlink_creator.py", line 181, in process_file
    dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<>/CineSync/MediaHub/processors/show_processor.py", line 51, in process_show
    anime_result = process_anime_show(src_file, root, file, dest_dir, actual_dir,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<>/CineSync/MediaHub/processors/anime_processor.py", line 129, in process_anime_show
    resolution = resolution.lower()
                 ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

possible solution to check None on resolution prior to operation.

**Comment by sureshfizzy** [comment]
> Traceback (most recent call last):
>   File "/home/<>/CineSync/MediaHub/processors/symlink_creator.py", line 181, in process_file
>     dest_file = process_show(src_file, root, file, dest_dir, actual_dir, tmdb_folder_id_enabled, rename_enabled, auto_select, dest_index, episode_match)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/<>/CineSync/MediaHub/processors/show_processor.py", line 51, in process_show
>     anime_result = process_anime_show(src_file, root, file, dest_dir, actual_dir,
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/<>/CineSync/MediaHub/processors/anime_processor.py", line 129, in process_anime_show
>     resolution = resolution.lower()
>                  ^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'lower'

Is this happening when resolution folder is used ?

**Comment by arao** [comment]
yes

**Comment by sureshfizzy** [comment]
> yes, possible solution
> 
> ```
> anime_processor.py#L129    resolution = resolution.lower() if resolution is not None else None
> ```

Yes, I just thought of that, and it should work. I'll update it accordingly. Thanks!

**Comment by sureshfizzy** [comment]
Updates have been pushed for this
