### ISSUE TITLE
Show filenames starting with a lowercase letter not getting symlinked properly

### ISSUE THREAD

**Issue by smoofus** [sureshfizzy/CineSync#39]
I'm having an issue with show filenames starting with a lowercase letter not getting symlinked.  I'll get one random episode in a season that has a file starting with a lowercase letter that is always mapped to S01E01...

For example, a number of episodes listed below start with a lowercase 's' 

```
Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
└── Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
└── Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
└── Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
└── Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
└── Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
└── Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv  
Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv  
└── Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv
secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
└── secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
└── secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
└── secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
└── secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
└── secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
└── secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
└── secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
└── secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv
```

Symlinks are created as expected for all the files with an uppercase 'S', however, only one of the files with a lowercase 's' gets linked and in all the cases I've seen so far its always mapped to S01E01  
```
├── secret level - S01E01 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv  
├── Secret Level - S01E01 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mk  
v  
├── Secret Level - S01E03 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mk  
v  
├── Secret Level - S01E04 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mk  
v  
├── Secret Level - S01E05 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mk  
v  
├── Secret Level - S01E06 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mk  
v  
├── Secret Level - S01E07 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mk  
v  
└── Secret Level - S01E12 [1080p].mkv -> /storage/media/debrid/__all__/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv/Secret Level S01E12 Spelunky Tally 1080  
p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv
```
I have a number of shows exhibiting this behavior.  Here is the [log](https://github.com/user-attachments/files/18168125/script.log) showing all the lowercase files being mapped to S01E01.  Oh, and great work! I'm excited to see this project grow, its perfect for my workflow!

**Comment by sureshfizzy** [comment]
Thanks for the logs, I'll drop a fix soon.

**Comment by sureshfizzy** [comment]
@smoofus  good to go, repull the new image.

**Comment by smoofus** [comment]
Just updated and ran a fresh scan.  The lowercase episodes are being linked but they are being put in a separate folder that does not get tagged appropriately.  Is that the expected behavior? 

```
Secret Level (2024) {tvdb-453280}
└── Season 1
    ├── Secret Level - S01E01 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E03 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E04 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E05 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E06 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E07 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    └── Secret Level - S01E12 [1080p].mkv -> /storage/media/debrid/__all__/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv

secret level
└── Season 1
    ├── secret level - s01e02 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e08 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e09 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e10 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e11 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e13 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e14 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    └── secret level - s01e15 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv

```

As an FYI, I did switch to the new custom movie/show folder option, which is awesome btw!  Mentinoing here as that is the only config change made for this fresh scan

**Comment by sureshfizzy** [comment]
Are you running docker ?

**Comment by smoofus** [comment]
No, I cloned the repo and I'm running directly

**Comment by sureshfizzy** [comment]
> No, I cloned the repo and I'm running directly

I had a hunch on this line, can you remove (, re.IGNORECASE) can give a try ?

Final line:

episode_number_match = re.search(r'E(\d+)', episode_identifier)

https://github.com/sureshfizzy/CineSync/blob/main/MediaHub/processors/show_processor.py#L265

**Comment by smoofus** [comment]
That fixed the multiple folder prob!  Only oddity is the lowercase files have a lower s/e in the season/episode tag but that's more of an OCD issue than functional... :) 

```
Secret Level (2024) {tvdb-453280}
└── Season 1
    ├── Secret Level - S01E01 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── secret level - s01e02 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── Secret Level - S01E03 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E04 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E05 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E06 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E07 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── secret level - s01e08 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e09 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e10 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e11 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── Secret Level - S01E12 [1080p].mkv -> /storage/media/debrid/__all__/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv
    ├── secret level - s01e13 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - s01e14 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    └── secret level - s01e15 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv

```

**Comment by sureshfizzy** [comment]
> That fixed the multiple folder prob! Only oddity is the lowercase files have a lower s/e in the season/episode tag but that's more of an OCD issue than functional... :)
> 
> ```
> Secret Level (2024) {tvdb-453280}
> └── Season 1
>     ├── Secret Level - S01E01 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── secret level - s01e02 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── Secret Level - S01E03 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── Secret Level - S01E04 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── Secret Level - S01E05 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── Secret Level - S01E06 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── Secret Level - S01E07 [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── secret level - s01e08 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── secret level - s01e09 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── secret level - s01e10 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── secret level - s01e11 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── Secret Level - S01E12 [1080p].mkv -> /storage/media/debrid/__all__/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv
>     ├── secret level - s01e13 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── secret level - s01e14 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     └── secret level - s01e15 [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv
> ```

episode_number_match = re.search(r'[Ee](\d+)', episode_identifier)

Can you try this ? Also sorry for the mess :(

**Comment by sureshfizzy** [comment]
Have you removed the symlink and readded again ? If that's the same result I'll check on it tomorrow..

**Comment by sureshfizzy** [comment]
> > Have you removed the symlink and readded again ? If that's the same result I'll check on it tomorrow..
> 
> Yes, I deleted the folder and ran a fresh scan. I would not consider this super critical as its more of a cosmetic thing than functional... thanks again for all the assistance!

I'll update the code tomorrow and let you know.

**Comment by sureshfizzy** [comment]
@smoofus Latest codes will work properly, you can try

**Comment by smoofus** [comment]
> @smoofus Latest codes will work properly, you can try

Nice!  I noticed the first letter is still lower but episode info is spot on! Even getting the episode title/name now as well!  Thanks again for the awesome work! 

```
Secret Level (2024) {tvdb-453280}
└── Season 1
    ├── Secret Level - S01E01 - Dungeons & Dragons: The Queen's Cradle [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── secret level - S01E02 - Sifu: It Takes a Life [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── Secret Level - S01E03 - New World: The Once and Future King [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E04 - Unreal Tournament: Xan [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E05 - Warhammer 40,000: And They Shall Know No Fear [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E06 - PAC-MAN: Circle [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── Secret Level - S01E07 - Crossfire: Good Conflict [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
    ├── secret level - S01E08 - Armored Core: Asset Management [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - S01E09 - The Outer Worlds: The Company We Keep [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - S01E10 - Mega Man: Start [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - S01E11 - Exodus: Odyssey [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── Secret Level - S01E12 - Spelunky: Tally [1080p].mkv -> /storage/media/debrid/__all__/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv
    ├── secret level - S01E13 - Concord: Tale of the Implacable [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    ├── secret level - S01E14 - Honor of Kings: The Way of All Things [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv
    └── secret level - S01E15 - Playtime: Fulfillment [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv

```

**Comment by sureshfizzy** [comment]
> > @smoofus Latest codes will work properly, you can try
> 
> Nice! I noticed the first letter is still lower but episode info is spot on! Even getting the episode title/name now as well! Thanks again for the awesome work!
> 
> ```
> Secret Level (2024) {tvdb-453280}
> └── Season 1
>     ├── Secret Level - S01E01 - Dungeons & Dragons: The Queen's Cradle [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── secret level - S01E02 - Sifu: It Takes a Life [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e02.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── Secret Level - S01E03 - New World: The Once and Future King [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E03.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── Secret Level - S01E04 - Unreal Tournament: Xan [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E04.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── Secret Level - S01E05 - Warhammer 40,000: And They Shall Know No Fear [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E05.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── Secret Level - S01E06 - PAC-MAN: Circle [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E06.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── Secret Level - S01E07 - Crossfire: Good Conflict [1080p].mkv -> /storage/media/debrid/__all__/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv/Secret.Level.S01E07.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-TURG.mkv
>     ├── secret level - S01E08 - Armored Core: Asset Management [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e08.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── secret level - S01E09 - The Outer Worlds: The Company We Keep [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e09.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── secret level - S01E10 - Mega Man: Start [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e10.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── secret level - S01E11 - Exodus: Odyssey [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e11.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── Secret Level - S01E12 - Spelunky: Tally [1080p].mkv -> /storage/media/debrid/__all__/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv/Secret Level S01E12 Spelunky Tally 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX[EZTVx.to].mkv
>     ├── secret level - S01E13 - Concord: Tale of the Implacable [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e13.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     ├── secret level - S01E14 - Honor of Kings: The Way of All Things [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e14.1080p.web.h264-successfulcrab[EZTVx.to].mkv
>     └── secret level - S01E15 - Playtime: Fulfillment [1080p].mkv -> /storage/media/debrid/__all__/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv/secret.level.s01e15.1080p.web.h264-successfulcrab[EZTVx.to].mkv
> ```

I'm still working on understanding the small letter at the beginning, but I’ll continue solving it as I progress
