### ISSUE TITLE
No Movies Folders 

### ISSUE THREAD

**Issue by seedboxer** [sureshfizzy/CineSync#41]
Nice project really helping me out but facing a bug.

I have setup something like this, very similar setup to all the zurg/All setups, but with Davdebrid 

But i am not seeing a Movies folder created - Shows -- Shows / UltraHD and FullHD are created fine, is there something in my env that can cause this, or will the Movies be processed last as alot going on atm on the server

```
# For detailed configuration explanations, visit:
# [Configuration Wiki or Documentation Link]

# ========================================
# Directory Paths
# ========================================
# Source directory for input files
SOURCE_DIR="/path/to/source/All"

# Destination directory for output files
DESTINATION_DIR="/path/to/destination/provider"

# Use source structure for organizing files
USE_SOURCE_STRUCTURE=false

# Custom folder paths for media organization
CINESYNC_LAYOUT=false
CUSTOM_SHOW_FOLDER=""
CUSTOM_MOVIE_FOLDER=""

# ========================================
# Logging Configuration
# ========================================
# Set the log level for application logging
LOG_LEVEL="INFO"

# ========================================
# Rclone Mount Configuration
# ========================================
RCLONE_MOUNT=false
MOUNT_CHECK_INTERVAL=30

# ========================================
# TMDb/IMDB Configuration
# ========================================
TMDB_API_KEY="your_tmdb_api_key"

ANIME_SCAN=false
TMDB_FOLDER_ID=true
IMDB_FOLDER_ID=true
TVDB_FOLDER_ID=true
RENAME_ENABLED=true
RENAME_TAGS=VideoCodec,AudioCodec,AudioAtmos,DynamicRange,AudioChannels,Resolution,Languages,ID

# ========================================
# Movie Collection Settings
# ========================================
MOVIE_COLLECTION_ENABLED=false

# ========================================
# System-based Configuration
# ========================================
RELATIVE_SYMLINK=false
MAX_PROCESSES=2

# ========================================
# File Handling Configuration
# ========================================
SKIP_EXTRAS_FOLDER=true
EXTRAS_MAX_SIZE_MB=250
SKIP_ADULT_PATTERNS=true

# ========================================
# Real-Time Monitoring Configuration
# ========================================
SLEEP_TIME=60

# ========================================
# Plex Integration Configuration
# ========================================
ENABLE_PLEX_UPDATE=true
PLEX_URL="http://localhost:32400"
PLEX_TOKEN="your_plex_token"

# ========================================
# Database Configuration
# ========================================
DB_THROTTLE_RATE=100
DB_MAX_RETRIES=10
DB_RETRY_DELAY=1.0
DB_BATCH_SIZE=1000
DB_MAX_WORKERS=4

```

**Comment by sureshfizzy** [comment]
Did you try symlinking a single movie file to verify working ? 

https://github.com/sureshfizzy/CineSync/wiki/Usage#single-filefolder-symlink-creation

**Comment by sureshfizzy** [comment]
That doesn't seem a valid movie name and you should not use ' ' for the mkv file alone. can you list your movies files and send pic ?

**Comment by seedboxer** [comment]
i set 

```
CINESYNC_LAYOUT=true
CUSTOM_SHOW_FOLDER="/mnt/external/debridlink/shows"
CUSTOM_MOVIE_FOLDER="/mnt/external/debridlink/movies"
```
Shows is listed but no movies.

![Capture](https://github.com/user-attachments/assets/1fc9deb8-639b-4718-9980-6b371fc3b5a9)

**Comment by seedboxer** [comment]
i noticed my debug log says 

`2024-12-19 13:45:39 [DEBUG] Checking directory '/mnt/external/downloads/db-link/All' for TV shows, mini-series, or anime.
`
is this interacting with Plex as i have not defined a folder for cinesync there  ?

**Comment by sureshfizzy** [comment]
Your configuration seems wrong.. you should set /mnt/external/debridlink/movies on source directory and update destination path to a different folder

Custom folder is just a modification for destination path.

**Comment by seedboxer** [comment]
i see this 

`2024-12-19 13:57:01 [DEBUG] Checking file: A.Different.Man.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv
2024-12-19 13:57:01 [DEBUG] File 'A.Different.Man.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv' does not match any pattern.
2024-12-19 13:57:01 [DEBUG] Checking file: A.Sudden.Case.Of.Christmas.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv
2024-12-19 13:57:01 [DEBUG] File 'A.Sudden.Case.Of.Christmas.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv' does not match any pattern.
2024-12-19 13:57:01 [DEBUG] Checking file: Absolution.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv
2024-12-19 13:57:01 [DEBUG] File 'Absolution.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv' does not match any pattern.
2024-12-19 13:57:01 [DEBUG] Checking file: Amityville.Where.The.Echo.Lives.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv
2024-12-19 13:57:01 [DEBUG] File 'Amityville.Where.The.Echo.Lives.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv' does not match any pattern.
2024-12-19 13:57:01 [DEBUG] Checking file: Apocalypse.Z.The.Beginning.Of.The.End.2024.2160p.4K.WEB.x265.10bit.AAC5.1-WORLD.mkv
2024-12-19 13:57:01 [DEBUG] File 'Apocalypse.Z.The.Beginning.Of.The.End.2024.2160p.4K.WEB.x265.10bit.AAC5.1-WORLD.mkv' does not match any pattern.
2024-12-19 13:57:01 [DEBUG] Checking file: Armor.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv
2024-12-19 13:57:01 [DEBUG] File 'Armor.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv' does not match any pattern.
2024-12-19 13:57:01 [DEBUG] Checking file: Blitz.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv
2024-12-19 13:57:01 [DEBUG] File 'Blitz.2024.2160p.4K.WEB.x265.10bit.AAC5.1-[YTS.MX].mkv' does not match any pattern.
`

**Comment by seedboxer** [comment]
also i see

`2024-12-19 13:57:01 [DEBUG] Checking directory '/mnt/external/downloads/db-link/Movies' for TV shows, mini-series, or anime.`

it does not mention 'Movies' is my settings in ENV confusing the code ?

**Comment by sureshfizzy** [comment]
Ok i found the issue, evey movie title has numbering at front as you displayed on the previous image 1. , 2., ..and so on. Due to this it is considering them as shows. Are those numbering present on the torrent file itself ?

**Comment by seedboxer** [comment]
Are you sure you are not seeing time for ls -al

![Capture](https://github.com/user-attachments/assets/77496046-d239-4541-9ad6-5ec45b6407dd)

**Comment by seedboxer** [comment]
could it be im running the script on a folder with already symlink and the ` is causing it to miss ?  But works with shows

**Comment by seedboxer** [comment]
For some crazy reason its placing movie files here 

![Capture](https://github.com/user-attachments/assets/bd4bb2af-41e4-4552-a1fa-312968dfc229)

**Comment by sureshfizzy** [comment]
Something is messed up for sure. Delete the above folder and Can you try symlinking single file for the smile2 mentioned above in the pic ?

Make sure you keep the entire path in double quote. python3 MediaHub/main.py "full/path/to/file.mkv"

**Comment by seedboxer** [comment]
i am using https://github.com/arvida42/davdebrid

It creates All, Movies, Shows similar to Zurg. No directories

my source is /mnt/external/downloads/db-link/All (or movies as testing)

my symlink is /mnt/external/debridlink/

**Comment by seedboxer** [comment]
any way to wipe the databse ? Maybe start again

**Comment by sureshfizzy** [comment]
Keep this way,

SOURCE_DIR=/mnt/external/downloads/debridlink/movies,/mnt/external/downloads/debridlink/shows

DESTINATION_DIR=/mnt/external/debridlink

For clearing the database, delete you current symlink folders and a folder named db in your project cloned directory.

**Comment by seedboxer** [comment]
set up in new container fresh start and behavioir is the same

**Comment by sureshfizzy** [comment]
> set up in new container fresh start and behavioir is the same

Reset the db again and do not run in docker this time, clone the project and run it locally for 1 movie file alone and send me the results.

**Comment by seedboxer** [comment]
Will try and do it now, and maybe go rclone direct

**Comment by seedboxer** [comment]
cleaned the library added 2 and now working, not sure what the issue was ? Not sure if it will freak out if it gets busy. 

Only 1 way to find out i guess.........

thanks for the great project

**Comment by sureshfizzy** [comment]
> cleaned the library added 2 and now working, not sure what the issue was ? Not sure if it will freak out if it gets busy.
> 
> Only 1 way to find out i guess.........
> 
> thanks for the great project

Its really strange lol, but I'm glad that it is working now.

**Comment by seedboxer** [comment]
Not sure why, after a few items added exact same error. Same folder created and movies moved there
'Civilization Express - The Great Feast of Movies (2022)' 
Will try direct rclone mount

**Comment by sureshfizzy** [comment]
> Not sure why, after a few items added exact same error. Same folder created and movies moved there 'Civilization Express - The Great Feast of Movies (2022)' Will try direct rclone mount

Do you have the log at which point this has been created ?

**Comment by seedboxer** [comment]
Took out davdebrid and went rclone direct via webdav at source and it working, not sure why davdebrid freaks it out so much

**Comment by sureshfizzy** [comment]
> Took out davdebrid and went rclone direct via webdav at source and it working, not sure why davdebrid freaks it out so much

Does davdebrid do anything different or it is the same functionality as zurg runs ?

**Comment by seedboxer** [comment]
Its supposed to be like zurg, i have never used cinesync with zurg, but clearly something that davdebrid is doing is freaking out cinesync. Id rather run cinesync than davdebrid anyway, as it much better for function in my opinion.

**Comment by seedboxer** [comment]
Cant lie this script is quite insane when partnered with mutliple rclone instances etc. Having doubts on the arrs stack now. Cant lie. Using with Plex_debrid

**Comment by sureshfizzy** [comment]
Perfect ! I'll also check on Davdebrid when I get the chance, as some users might still be relying on it

**Comment by seedboxer** [comment]
Yes maybe worth a look if you get a chance, maybe you can work it out, such a strange bug. but the filtering on it is terrible and its perhaps badly written. i think it must be alot behind zurg. Your a coder so you will work it out quicker than me.
