### ISSUE TITLE
Could we add postgres ?

### ISSUE THREAD

**Issue by seedboxer** [sureshfizzy/CineSync#42]
Love the script but noticed on restart of rclone mount it rewrites the symlinks, this is a lot of read and writes.

Could we add a postgres or similar and maybe a maintenance script to check to missing links or deleted perhaps once a week, to prevent the repeated rewrites ? 

**CHAT GPT SUMMARY (I WONT INSULT YOU AND PRETEND I WROTE IT)**

**Issue:**

    When rclone mount restarts, it rewrites symlinks, leading to unnecessary read and write operations. This happens each time the mount restarts.

**Proposed Solution:**

    Use a Database (PostgreSQL):
        Instead of having rclone continuously recheck and recreate symlinks, we can track the symlinks in a database (e.g., PostgreSQL).
        This way, only missing or deleted symlinks are checked, and we can maintain a persistent record of which symlinks are valid.
    Maintenance Script:
        A script can be scheduled (e.g., using cron or a Docker scheduled task) to run weekly to check for any missing or deleted symlinks. The script would:
            Compare current symlinks with the database record.
            Recreate symlinks only if they are missing or deleted.
        This reduces redundant read and write operations that happen during every mount restart.

**Implementation Plan**:

    PostgreSQL Database:
        Set up a PostgreSQL container to track symlink paths and their target files.
    Symlink Tracking:
        When a symlink is created or modified, record the symlink path and target in the database.
    Maintenance Script:
        The script runs weekly to:
            Query the database for all known symlinks.
            Check if each symlink still exists and points to the correct target.
            If a symlink is missing or broken, recreate it and update the database.
    **Benefits**:
        By tracking symlinks in the database, you reduce unnecessary file system operations.
        Only missing or broken symlinks are processed.
        The process of checking and repairing symlinks becomes more efficient and less resource-intensive

**Comment by sureshfizzy** [comment]
I am already using sql db for checking and saving symlinks which prevents read and write during restart. I suggest to check the configuration to see what is the issue...

Verify if you have a folder named db and database files present inside it.

**Comment by seedboxer** [comment]
Yes it must be there, but just noticed some rescanning on restart !

**Comment by sureshfizzy** [comment]
> Yes it must be there, but just noticed some rescanning on restart !

Are you using torbox ?

**Comment by seedboxer** [comment]
> > Yes it must be there, but just noticed some rescanning on restart !
> 
> Are you using torbox ?

using 4 debrid services including torbox atm, just doing some testing RD with zurg. TB with rclone ftp. and AD and DL via thier own webdav using rclone. All mounted in different folders.

**Comment by seedboxer** [comment]
emailed you....

**Comment by seedboxer** [comment]
pinged you msg !
