### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by scumball** [sureshfizzy/CineSync#8]
Any chance this could be set to use this naming convention so it could be used to move libraries between Plex debrid and the new riven app?

movies
- Movie Title (year) (imdbid-ttxxxxx)
---- Movie Title (year) (imdbid-ttxxxxx).mkv

shows
-Show Title (year) (imdbid-ttxxxxx)
---- Season 01
  ----- Show Title - sO1e01 - episode title.mkv

**Comment by sureshfizzy** [comment]
I am using tmdb for renaming since that was the easiest way for files. I'll check one for IMDb..btw is the IMDb I'd necessary ? 🤔

**Comment by scumball** [comment]
I think for this project it is, I'm just looking at simple ways to move from Plex debrid to riven without nuking my existing library. I understand that's not the remit of your project but thought I'd ask if it was a simple enough change...

**Comment by sureshfizzy** [comment]
> I think for this project it is, I'm just looking at simple ways to move from Plex debrid to riven without nuking my existing library. I understand that's not the remit of your project but thought I'd ask if it was a simple enough change...

Might be simple but I'm not aware of it for sure until I start working on this. I'll try to add some additional flags and config filters so that you can pick as per your need.

**Comment by scumball** [comment]
hey found this tool so probably not needed thanks
https://github.com/mercuryy-1337/tmdb-tv-organiser
